const data = {
    "msg": "",
    "flag": "00",
    "currPage": 1,
    "pages": 1,
    "pageSize": 25,
    "rowCount": 19,
    "device": {
        "createDate": "2020-12-22 18:02:23",
        "defaultTimescale": "120",
        "deviceName": "智能家居",
        "deviceNo": "UOWJ1448J2CDVZ2W",
        "id": 200063478,
        "iocUrl": "/images/default/non_online-1.png",
        "iotDeviceId": "",
        "isAlarms": "0",
        "isDelete": 0,
        "isLine": 0,
        "lat": "22.532257",
        "linktype": "tcp",
        "lng": "113.394786",
        "parentUser": 0,
        "productId": "",
        "productType": "",
        "protocolLabel": "",
        "remark": "",
        "sensorsList": [
            {
                "accessToken": "",
                "appkey": "",
                "bias": "",
                "decimalPlacse": "0",
                "deviceId": 200063478,
                "deviceName": "智能家居",
                "fialtime": "",
                "flag": "",
                "heartbeatDate": "2020-12-27 09:58:58",
                "hls": "",
                "id": 200477739,
                "iocUrl": "/images/default/temperature.png",
                "isAlarms": 0,
                "isDelete": 0,
                "isLine": 0,
                "isMapping": 0,
                "lat": "null",
                "live": "",
                "lng": "null",
                "openysId": 0,
                "ordernum": 0,
                "replay": "",
                "rtmp": "",
                "secret": "",
                "send_data_type": "",
                "send_value": "",
                "sensorMapping": null,
                "sensorName": "传感器-温度",
                "sensorTypeId": 1,
                "switch_off": "",
                "switch_on": "",
                "switcher": "null",
                "tp_flag": "",
                "unit": "%",
                "updateDate": "2020-12-27 10:11:25",
                "userId": 0,
                "userName": "13724932914",
                "value": "44"
            },
            {
                "accessToken": "",
                "appkey": "",
                "bias": "",
                "decimalPlacse": "0",
                "deviceId": 200063478,
                "deviceName": "智能家居",
                "fialtime": "",
                "flag": "",
                "heartbeatDate": "2020-12-27 09:58:58",
                "hls": "",
                "id": 200477740,
                "iocUrl": "/images/default/temperature.png",
                "isAlarms": 0,
                "isDelete": 0,
                "isLine": 0,
                "isMapping": 0,
                "lat": "null",
                "live": "",
                "lng": "null",
                "openysId": 0,
                "ordernum": 0,
                "replay": "",
                "rtmp": "",
                "secret": "",
                "send_data_type": "",
                "send_value": "",
                "sensorMapping": null,
                "sensorName": "传感器-湿度",
                "sensorTypeId": 1,
                "switch_off": "",
                "switch_on": "",
                "switcher": "null",
                "tp_flag": "",
                "unit": "%",
                "updateDate": "2020-12-27 10:11:25",
                "userId": 0,
                "userName": "13724932914",
                "value": "44"
            },
            {
                "accessToken": "",
                "appkey": "",
                "bias": "",
                "decimalPlacse": "0",
                "deviceId": 200063478,
                "deviceName": "智能家居",
                "fialtime": "",
                "flag": "",
                "heartbeatDate": "2020-12-27 09:58:58",
                "hls": "",
                "id": 200477741,
                "iocUrl": "/images/default/temperature.png",
                "isAlarms": 1,
                "isDelete": 0,
                "isLine": 0,
                "isMapping": 0,
                "lat": "null",
                "live": "",
                "lng": "null",
                "openysId": 0,
                "ordernum": 0,
                "replay": "",
                "rtmp": "",
                "secret": "",
                "send_data_type": "",
                "send_value": "",
                "sensorMapping": null,
                "sensorName": "传感器-空气污染指数",
                "sensorTypeId": 1,
                "switch_off": "",
                "switch_on": "",
                "switcher": "null",
                "tp_flag": "",
                "unit": "%",
                "updateDate": "2020-12-27 10:11:25",
                "userId": 0,
                "userName": "13724932914",
                "value": "22"
            },
            {
                "accessToken": "",
                "appkey": "",
                "bias": "",
                "decimalPlacse": "",
                "deviceId": 200063478,
                "deviceName": "智能家居",
                "fialtime": "",
                "flag": "",
                "heartbeatDate": "2020-12-27 09:58:58",
                "hls": "",
                "id": 200477735,
                "iocUrl": "/images/default/temperature.png",
                "isAlarms": 0,
                "isDelete": 0,
                "isLine": 0,
                "isMapping": 0,
                "lat": "null",
                "live": "",
                "lng": "null",
                "openysId": 0,
                "ordernum": 1,
                "replay": "",
                "rtmp": "",
                "secret": "",
                "send_data_type": "",
                "send_value": "",
                "sensorMapping": null,
                "sensorName": "客厅-吊灯",
                "sensorTypeId": 2,
                "switch_off": "",
                "switch_on": "",
                "switcher": "0",
                "tp_flag": "",
                "unit": "",
                "updateDate": "2020-12-27 10:11:25",
                "userId": 0,
                "userName": "13724932914",
                "value": "null"
            },
            {
                "accessToken": "",
                "appkey": "",
                "bias": "",
                "decimalPlacse": "",
                "deviceId": 200063478,
                "deviceName": "智能家居",
                "fialtime": "",
                "flag": "",
                "heartbeatDate": "2020-12-27 09:58:58",
                "hls": "",
                "id": 200477736,
                "iocUrl": "/images/default/temperature.png",
                "isAlarms": 0,
                "isDelete": 0,
                "isLine": 0,
                "isMapping": 0,
                "lat": "null",
                "live": "",
                "lng": "null",
                "openysId": 0,
                "ordernum": 1,
                "replay": "",
                "rtmp": "",
                "secret": "",
                "send_data_type": "",
                "send_value": "",
                "sensorMapping": null,
                "sensorName": "客厅-空调",
                "sensorTypeId": 2,
                "switch_off": "",
                "switch_on": "",
                "switcher": "1",
                "tp_flag": "",
                "unit": "",
                "updateDate": "2020-12-27 10:11:25",
                "userId": 0,
                "userName": "13724932914",
                "value": "null"
            },
            {
                "accessToken": "",
                "appkey": "",
                "bias": "",
                "decimalPlacse": "",
                "deviceId": 200063478,
                "deviceName": "智能家居",
                "fialtime": "",
                "flag": "",
                "heartbeatDate": "2020-12-27 09:58:58",
                "hls": "",
                "id": 200477737,
                "iocUrl": "/images/default/temperature.png",
                "isAlarms": 0,
                "isDelete": 0,
                "isLine": 0,
                "isMapping": 0,
                "lat": "null",
                "live": "",
                "lng": "null",
                "openysId": 0,
                "ordernum": 1,
                "replay": "",
                "rtmp": "",
                "secret": "",
                "send_data_type": "",
                "send_value": "",
                "sensorMapping": null,
                "sensorName": "客厅-扫地机器人",
                "sensorTypeId": 2,
                "switch_off": "",
                "switch_on": "",
                "switcher": "1",
                "tp_flag": "",
                "unit": "",
                "updateDate": "2020-12-27 10:11:25",
                "userId": 0,
                "userName": "13724932914",
                "value": "null"
            },
            {
                "accessToken": "",
                "appkey": "",
                "bias": "",
                "decimalPlacse": "",
                "deviceId": 200063478,
                "deviceName": "智能家居",
                "fialtime": "",
                "flag": "",
                "heartbeatDate": "2020-12-27 09:58:58",
                "hls": "",
                "id": 200477738,
                "iocUrl": "/images/default/temperature.png",
                "isAlarms": 0,
                "isDelete": 0,
                "isLine": 0,
                "isMapping": 0,
                "lat": "null",
                "live": "",
                "lng": "null",
                "openysId": 0,
                "ordernum": 1,
                "replay": "",
                "rtmp": "",
                "secret": "",
                "send_data_type": "",
                "send_value": "",
                "sensorMapping": null,
                "sensorName": "客厅-空气净化器",
                "sensorTypeId": 2,
                "switch_off": "",
                "switch_on": "",
                "switcher": "1",
                "tp_flag": "",
                "unit": "",
                "updateDate": "2020-12-27 10:11:25",
                "userId": 0,
                "userName": "13724932914",
                "value": "null"
            },
            {
                "accessToken": "",
                "appkey": "",
                "bias": "",
                "decimalPlacse": "0",
                "deviceId": 200063478,
                "deviceName": "智能家居",
                "fialtime": "",
                "flag": "",
                "heartbeatDate": "2020-12-27 09:58:58",
                "hls": "",
                "id": 200477742,
                "iocUrl": "/images/default/temperature.png",
                "isAlarms": 0,
                "isDelete": 0,
                "isLine": 0,
                "isMapping": 0,
                "lat": "null",
                "live": "",
                "lng": "null",
                "openysId": 0,
                "ordernum": 2,
                "replay": "",
                "rtmp": "",
                "secret": "",
                "send_data_type": "",
                "send_value": "",
                "sensorMapping": null,
                "sensorName": "厨房-可燃气体浓度传感器",
                "sensorTypeId": 1,
                "switch_off": "",
                "switch_on": "",
                "switcher": "null",
                "tp_flag": "",
                "unit": "%",
                "updateDate": "2020-12-27 10:11:25",
                "userId": 0,
                "userName": "13724932914",
                "value": "38"
            },
            {
                "accessToken": "",
                "appkey": "",
                "bias": "",
                "decimalPlacse": "",
                "deviceId": 200063478,
                "deviceName": "智能家居",
                "fialtime": "",
                "flag": "",
                "heartbeatDate": "2020-12-27 09:58:58",
                "hls": "",
                "id": 200477748,
                "iocUrl": "/images/default/temperature.png",
                "isAlarms": 0,
                "isDelete": 0,
                "isLine": 0,
                "isMapping": 0,
                "lat": "null",
                "live": "",
                "lng": "null",
                "openysId": 0,
                "ordernum": 2,
                "replay": "",
                "rtmp": "",
                "secret": "",
                "send_data_type": "",
                "send_value": "",
                "sensorMapping": null,
                "sensorName": "厨房-电饭煲",
                "sensorTypeId": 2,
                "switch_off": "",
                "switch_on": "",
                "switcher": "1",
                "tp_flag": "",
                "unit": "",
                "updateDate": "2020-12-27 10:11:25",
                "userId": 0,
                "userName": "13724932914",
                "value": "null"
            },
            {
                "accessToken": "",
                "appkey": "",
                "bias": "",
                "decimalPlacse": "",
                "deviceId": 200063478,
                "deviceName": "智能家居",
                "fialtime": "",
                "flag": "",
                "heartbeatDate": "2020-12-27 09:58:58",
                "hls": "",
                "id": 200477749,
                "iocUrl": "/images/default/temperature.png",
                "isAlarms": 0,
                "isDelete": 0,
                "isLine": 0,
                "isMapping": 0,
                "lat": "null",
                "live": "",
                "lng": "null",
                "openysId": 0,
                "ordernum": 2,
                "replay": "",
                "rtmp": "",
                "secret": "",
                "send_data_type": "",
                "send_value": "",
                "sensorMapping": null,
                "sensorName": "厨房-微波炉",
                "sensorTypeId": 2,
                "switch_off": "",
                "switch_on": "",
                "switcher": "1",
                "tp_flag": "",
                "unit": "",
                "updateDate": "2020-12-27 10:11:25",
                "userId": 0,
                "userName": "13724932914",
                "value": "null"
            },
            {
                "accessToken": "",
                "appkey": "",
                "bias": "",
                "decimalPlacse": "",
                "deviceId": 200063478,
                "deviceName": "智能家居",
                "fialtime": "",
                "flag": "",
                "heartbeatDate": "2020-12-27 09:58:58",
                "hls": "",
                "id": 200477750,
                "iocUrl": "/images/default/temperature.png",
                "isAlarms": 0,
                "isDelete": 0,
                "isLine": 0,
                "isMapping": 0,
                "lat": "null",
                "live": "",
                "lng": "null",
                "openysId": 0,
                "ordernum": 3,
                "replay": "",
                "rtmp": "",
                "secret": "",
                "send_data_type": "",
                "send_value": "",
                "sensorMapping": null,
                "sensorName": "书房-吊灯",
                "sensorTypeId": 2,
                "switch_off": "",
                "switch_on": "",
                "switcher": "1",
                "tp_flag": "",
                "unit": "",
                "updateDate": "2020-12-27 10:11:25",
                "userId": 0,
                "userName": "13724932914",
                "value": "null"
            },
            {
                "accessToken": "",
                "appkey": "",
                "bias": "",
                "decimalPlacse": "",
                "deviceId": 200063478,
                "deviceName": "智能家居",
                "fialtime": "",
                "flag": "",
                "heartbeatDate": "2020-12-27 09:58:58",
                "hls": "",
                "id": 200477751,
                "iocUrl": "/images/default/temperature.png",
                "isAlarms": 0,
                "isDelete": 0,
                "isLine": 0,
                "isMapping": 0,
                "lat": "null",
                "live": "",
                "lng": "null",
                "openysId": 0,
                "ordernum": 3,
                "replay": "",
                "rtmp": "",
                "secret": "",
                "send_data_type": "",
                "send_value": "",
                "sensorMapping": null,
                "sensorName": "书房-智能插座",
                "sensorTypeId": 2,
                "switch_off": "",
                "switch_on": "",
                "switcher": "1",
                "tp_flag": "",
                "unit": "",
                "updateDate": "2020-12-27 10:11:25",
                "userId": 0,
                "userName": "13724932914",
                "value": "null"
            },
            {
                "accessToken": "",
                "appkey": "",
                "bias": "",
                "decimalPlacse": "",
                "deviceId": 200063478,
                "deviceName": "智能家居",
                "fialtime": "",
                "flag": "",
                "heartbeatDate": "2020-12-27 09:58:58",
                "hls": "",
                "id": 200477752,
                "iocUrl": "/images/default/temperature.png",
                "isAlarms": 0,
                "isDelete": 0,
                "isLine": 0,
                "isMapping": 0,
                "lat": "null",
                "live": "",
                "lng": "null",
                "openysId": 0,
                "ordernum": 3,
                "replay": "",
                "rtmp": "",
                "secret": "",
                "send_data_type": "",
                "send_value": "",
                "sensorMapping": null,
                "sensorName": "书房-空调",
                "sensorTypeId": 2,
                "switch_off": "",
                "switch_on": "",
                "switcher": "0",
                "tp_flag": "",
                "unit": "",
                "updateDate": "2020-12-27 10:11:25",
                "userId": 0,
                "userName": "13724932914",
                "value": "null"
            },
            {
                "accessToken": "",
                "appkey": "",
                "bias": "",
                "decimalPlacse": "",
                "deviceId": 200063478,
                "deviceName": "智能家居",
                "fialtime": "",
                "flag": "",
                "heartbeatDate": "2020-12-27 09:58:58",
                "hls": "",
                "id": 200477747,
                "iocUrl": "/images/default/temperature.png",
                "isAlarms": 0,
                "isDelete": 0,
                "isLine": 0,
                "isMapping": 0,
                "lat": "null",
                "live": "",
                "lng": "null",
                "openysId": 0,
                "ordernum": 4,
                "replay": "",
                "rtmp": "",
                "secret": "",
                "send_data_type": "",
                "send_value": "",
                "sensorMapping": null,
                "sensorName": "卫浴-洗衣机",
                "sensorTypeId": 2,
                "switch_off": "",
                "switch_on": "",
                "switcher": "0",
                "tp_flag": "",
                "unit": "",
                "updateDate": "2020-12-27 10:11:25",
                "userId": 0,
                "userName": "13724932914",
                "value": "null"
            },
            {
                "accessToken": "",
                "appkey": "",
                "bias": "",
                "decimalPlacse": "",
                "deviceId": 200063478,
                "deviceName": "智能家居",
                "fialtime": "",
                "flag": "",
                "heartbeatDate": "2020-12-27 09:58:58",
                "hls": "",
                "id": 200477753,
                "iocUrl": "/images/default/temperature.png",
                "isAlarms": 0,
                "isDelete": 0,
                "isLine": 0,
                "isMapping": 0,
                "lat": "null",
                "live": "",
                "lng": "null",
                "openysId": 0,
                "ordernum": 4,
                "replay": "",
                "rtmp": "",
                "secret": "",
                "send_data_type": "",
                "send_value": "",
                "sensorMapping": null,
                "sensorName": "卫浴-浴缸注水",
                "sensorTypeId": 2,
                "switch_off": "",
                "switch_on": "",
                "switcher": "1",
                "tp_flag": "",
                "unit": "",
                "updateDate": "2020-12-27 10:11:25",
                "userId": 0,
                "userName": "13724932914",
                "value": "null"
            },
            {
                "accessToken": "",
                "appkey": "",
                "bias": "",
                "decimalPlacse": "0",
                "deviceId": 200063478,
                "deviceName": "智能家居",
                "fialtime": "",
                "flag": "",
                "heartbeatDate": "2020-12-27 09:58:58",
                "hls": "",
                "id": 200477754,
                "iocUrl": "/images/default/temperature.png",
                "isAlarms": 0,
                "isDelete": 0,
                "isLine": 0,
                "isMapping": 0,
                "lat": "null",
                "live": "",
                "lng": "null",
                "openysId": 0,
                "ordernum": 4,
                "replay": "",
                "rtmp": "",
                "secret": "",
                "send_data_type": "",
                "send_value": "",
                "sensorMapping": null,
                "sensorName": "卫浴-浴缸水温",
                "sensorTypeId": 1,
                "switch_off": "",
                "switch_on": "",
                "switcher": "null",
                "tp_flag": "",
                "unit": "度",
                "updateDate": "2020-12-27 10:11:25",
                "userId": 0,
                "userName": "13724932914",
                "value": "78"
            },
            {
                "accessToken": "",
                "appkey": "",
                "bias": "",
                "decimalPlacse": "",
                "deviceId": 200063478,
                "deviceName": "智能家居",
                "fialtime": "",
                "flag": "",
                "heartbeatDate": "2020-12-27 09:58:58",
                "hls": "",
                "id": 200477755,
                "iocUrl": "/images/default/temperature.png",
                "isAlarms": 0,
                "isDelete": 0,
                "isLine": 0,
                "isMapping": 0,
                "lat": "null",
                "live": "",
                "lng": "null",
                "openysId": 0,
                "ordernum": 5,
                "replay": "",
                "rtmp": "",
                "secret": "",
                "send_data_type": "",
                "send_value": "",
                "sensorMapping": null,
                "sensorName": "卧室-吊灯",
                "sensorTypeId": 2,
                "switch_off": "",
                "switch_on": "",
                "switcher": "1",
                "tp_flag": "",
                "unit": "",
                "updateDate": "2020-12-27 10:11:25",
                "userId": 0,
                "userName": "13724932914",
                "value": "null"
            },
            {
                "accessToken": "",
                "appkey": "",
                "bias": "",
                "decimalPlacse": "",
                "deviceId": 200063478,
                "deviceName": "智能家居",
                "fialtime": "",
                "flag": "",
                "heartbeatDate": "2020-12-27 09:58:58",
                "hls": "",
                "id": 200477756,
                "iocUrl": "/images/default/temperature.png",
                "isAlarms": 0,
                "isDelete": 0,
                "isLine": 0,
                "isMapping": 0,
                "lat": "null",
                "live": "",
                "lng": "null",
                "openysId": 0,
                "ordernum": 5,
                "replay": "",
                "rtmp": "",
                "secret": "",
                "send_data_type": "",
                "send_value": "",
                "sensorMapping": null,
                "sensorName": "卧室-窗帘",
                "sensorTypeId": 2,
                "switch_off": "",
                "switch_on": "",
                "switcher": "0",
                "tp_flag": "",
                "unit": "",
                "updateDate": "2020-12-27 10:11:25",
                "userId": 0,
                "userName": "13724932914",
                "value": "null"
            },
            {
                "accessToken": "",
                "appkey": "",
                "bias": "",
                "decimalPlacse": "",
                "deviceId": 200063478,
                "deviceName": "智能家居",
                "fialtime": "",
                "flag": "",
                "heartbeatDate": "2020-12-27 09:58:58",
                "hls": "",
                "id": 200477757,
                "iocUrl": "/images/default/temperature.png",
                "isAlarms": 0,
                "isDelete": 0,
                "isLine": 0,
                "isMapping": 0,
                "lat": "null",
                "live": "",
                "lng": "null",
                "openysId": 0,
                "ordernum": 5,
                "replay": "",
                "rtmp": "",
                "secret": "",
                "send_data_type": "",
                "send_value": "",
                "sensorMapping": null,
                "sensorName": "卧室-空调",
                "sensorTypeId": 2,
                "switch_off": "",
                "switch_on": "",
                "switcher": "1",
                "tp_flag": "",
                "unit": "",
                "updateDate": "2020-12-27 10:11:25",
                "userId": 0,
                "userName": "13724932914",
                "value": "null"
            }
        ],
        "userId": 200028164,
        "userName": "13724932914"
    }
}

console.log(data)